name: PowerShell Test

on:
  workflow_dispatch:

jobs:
  7z:
    name: 7z-zstd
    runs-on: windows-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install 7z-zstd
      shell: pwsh
      run: |
        Write-Host -Message "pws: $pws";
        $PSVersionTable | Out-Host | Out-Null;
        Get-ChildItem -Path .\
    - name: Install 7z-zstd
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri 'https://github.com/mcmilk/7-Zip-zstd/releases/download/v21.03-v1.5.0-R2/7z21.03-zstd-x64.exe' -OutFile .\out.exe
        .\out.exe /S
    - name: Check 7z-zstd
      shell: pwsh
      run: |
        $7z = Get-Command -Name '7z' -ErrorAction SilentlyContinue;
        Write-Host -Message "7z in PATH? $($null -ne $7z)" | Out-Null;
        $7z = Get-Command -Name "$env:ProgramFiles\7-Zip-Zstandard\7z.exe" -ErrorAction SilentlyContinue;
        Write-Host -Message "7z in ProgramFiles? $($null -ne $7z)" | Out-Null;
